language: csharp
dotnet: 5.0
branches:
  only:
    - master
sudo: false
env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet build MyECommerceSample.sln -c Release

  - dotnet test ../MyECommerceSample /p:CollectCoverage=true /p:ExcludeByFile=\"**/Migrations/*.cs,**/Startup.cs,**/Program.cs\"  /p:CoverletOutputFormat=opencover
after_script:
  - bash <(curl -s https://codecov.io/bash)
